// Autogenerated from Pigeon (v26.1.10), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, omit_obvious_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


class _PigeonConfig {
  _PigeonConfig({
    this.sentinel,
  });

  String? sentinel;

  List<Object?> _toList() {
    return <Object?>[
      sentinel,
    ];
  }

  Object encode() {
    return _toList();  }

  static _PigeonConfig decode(Object result) {
    result as List<Object?>;
    return _PigeonConfig(
      sentinel: result[0] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! _PigeonConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class NativeAlbumRecord {
  NativeAlbumRecord({
    required this.bucketId,
    required this.bucketName,
    required this.videoCount,
    required this.latestDateAddedSeconds,
  });

  String bucketId;

  String bucketName;

  int videoCount;

  int latestDateAddedSeconds;

  List<Object?> _toList() {
    return <Object?>[
      bucketId,
      bucketName,
      videoCount,
      latestDateAddedSeconds,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeAlbumRecord decode(Object result) {
    result as List<Object?>;
    return NativeAlbumRecord(
      bucketId: result[0]! as String,
      bucketName: result[1]! as String,
      videoCount: result[2]! as int,
      latestDateAddedSeconds: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeAlbumRecord || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class NativeVideoRecord {
  NativeVideoRecord({
    required this.id,
    required this.path,
    required this.name,
    required this.bucketId,
    required this.bucketName,
    required this.durationMs,
    required this.size,
    required this.dateAdded,
  });

  String id;

  String path;

  String name;

  String bucketId;

  String bucketName;

  int durationMs;

  int size;

  int dateAdded;

  List<Object?> _toList() {
    return <Object?>[
      id,
      path,
      name,
      bucketId,
      bucketName,
      durationMs,
      size,
      dateAdded,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeVideoRecord decode(Object result) {
    result as List<Object?>;
    return NativeVideoRecord(
      id: result[0]! as String,
      path: result[1]! as String,
      name: result[2]! as String,
      bucketId: result[3]! as String,
      bucketName: result[4]! as String,
      durationMs: result[5]! as int,
      size: result[6]! as int,
      dateAdded: result[7]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeVideoRecord || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is _PigeonConfig) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is NativeAlbumRecord) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is NativeVideoRecord) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return _PigeonConfig.decode(readValue(buffer)!);
      case 130:
        return NativeAlbumRecord.decode(readValue(buffer)!);
      case 131:
        return NativeVideoRecord.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class MediaStoreAlbumsApi {
  /// Constructor for [MediaStoreAlbumsApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MediaStoreAlbumsApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<bool> hasVideoPermission() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.pixelplay.MediaStoreAlbumsApi.hasVideoPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    !;
    return pigeonVar_replyValue as bool;
  }

  Future<bool> requestVideoPermission() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.pixelplay.MediaStoreAlbumsApi.requestVideoPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    !;
    return pigeonVar_replyValue as bool;
  }

  Future<List<NativeAlbumRecord>> scanLocalVideoAlbums() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.pixelplay.MediaStoreAlbumsApi.scanLocalVideoAlbums$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    !;
    return (pigeonVar_replyValue as List<Object?>).cast<NativeAlbumRecord>();
  }

  Future<List<NativeVideoRecord>> scanAlbumVideos(String bucketId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.pixelplay.MediaStoreAlbumsApi.scanAlbumVideos$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[bucketId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    !;
    return (pigeonVar_replyValue as List<Object?>).cast<NativeVideoRecord>();
  }
}
