// Autogenerated from Pigeon (v26.1.10), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package media.gabriel.pixelplay.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MediaStoreAlbumsApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class _PigeonConfig (
  val sentinel: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): _PigeonConfig {
      val sentinel = pigeonVar_list[0] as String?
      return _PigeonConfig(sentinel)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sentinel,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is _PigeonConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return MediaStoreAlbumsApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeAlbumRecord (
  val bucketId: String,
  val bucketName: String,
  val videoCount: Long,
  val latestDateAddedSeconds: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAlbumRecord {
      val bucketId = pigeonVar_list[0] as String
      val bucketName = pigeonVar_list[1] as String
      val videoCount = pigeonVar_list[2] as Long
      val latestDateAddedSeconds = pigeonVar_list[3] as Long
      return NativeAlbumRecord(bucketId, bucketName, videoCount, latestDateAddedSeconds)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      bucketId,
      bucketName,
      videoCount,
      latestDateAddedSeconds,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeAlbumRecord) {
      return false
    }
    if (this === other) {
      return true
    }
    return MediaStoreAlbumsApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeVideoRecord (
  val id: String,
  val path: String,
  val name: String,
  val bucketId: String,
  val bucketName: String,
  val durationMs: Long,
  val size: Long,
  val dateAdded: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeVideoRecord {
      val id = pigeonVar_list[0] as String
      val path = pigeonVar_list[1] as String
      val name = pigeonVar_list[2] as String
      val bucketId = pigeonVar_list[3] as String
      val bucketName = pigeonVar_list[4] as String
      val durationMs = pigeonVar_list[5] as Long
      val size = pigeonVar_list[6] as Long
      val dateAdded = pigeonVar_list[7] as Long
      return NativeVideoRecord(id, path, name, bucketId, bucketName, durationMs, size, dateAdded)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      path,
      name,
      bucketId,
      bucketName,
      durationMs,
      size,
      dateAdded,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeVideoRecord) {
      return false
    }
    if (this === other) {
      return true
    }
    return MediaStoreAlbumsApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class media_store_albums_apiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          _PigeonConfig.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAlbumRecord.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeVideoRecord.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is _PigeonConfig -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is NativeAlbumRecord -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is NativeVideoRecord -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface MediaStoreAlbumsApi {
  fun hasVideoPermission(callback: (Result<Boolean>) -> Unit)
  fun requestVideoPermission(callback: (Result<Boolean>) -> Unit)
  fun scanLocalVideoAlbums(callback: (Result<List<NativeAlbumRecord>>) -> Unit)
  fun scanAlbumVideos(bucketId: String, callback: (Result<List<NativeVideoRecord>>) -> Unit)

  companion object {
    /** The codec used by MediaStoreAlbumsApi. */
    val codec: MessageCodec<Any?> by lazy {
      media_store_albums_apiPigeonCodec()
    }
    /** Sets up an instance of `MediaStoreAlbumsApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MediaStoreAlbumsApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pixelplay.MediaStoreAlbumsApi.hasVideoPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.hasVideoPermission{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MediaStoreAlbumsApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MediaStoreAlbumsApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pixelplay.MediaStoreAlbumsApi.requestVideoPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestVideoPermission{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MediaStoreAlbumsApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MediaStoreAlbumsApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pixelplay.MediaStoreAlbumsApi.scanLocalVideoAlbums$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.scanLocalVideoAlbums{ result: Result<List<NativeAlbumRecord>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MediaStoreAlbumsApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MediaStoreAlbumsApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pixelplay.MediaStoreAlbumsApi.scanAlbumVideos$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val bucketIdArg = args[0] as String
            api.scanAlbumVideos(bucketIdArg) { result: Result<List<NativeVideoRecord>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MediaStoreAlbumsApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MediaStoreAlbumsApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
